spring:
  application:
    name: devpulse

  datasource:
    url: jdbc:postgresql://localhost:5432/devpulse
    username: devpulse_user
    password: devpulse_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.devpulse: DEBUG
    org.hibernate.SQL: DEBUG