spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: devpulse

  datasource:
    url: jdbc:postgresql://localhost:5433/devpulse
    username: devpulse_user
    password: devpulse_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.devpulse: DEBUG
    org.hibernate.SQL: DEBUG

devpulse:
  github:
    webhook-secret: ${GITHUB_WEBHOOK_SECRET:}
  gemini:
    api-key: ${GEMINI_API_KEY:your-gemini-api-key}
    api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

  slack:
    webhook-url: ${SLACK_WEBHOOK_URL:your-slack-webhook-url}
  scheduling:
    analysis-cron: "0 0 2 * * *"
    report-cron: "0 0 9 * * MON"